namespace EduSync.Modules.Students.Application.Dtos;

public sealed record StudentDto(
    string Id,
    string FirstName,
    string LastName,
    string Name,
    string Class,
    string Section,
    string RollNo,
    string AdmissionNo,
    string Email,
    string? Phone,
    string? DateOfBirth,
    string? Gender,
    string? BloodGroup,
    string? Address,
    string? ParentName,
    string? ParentPhone,
    string? ParentEmail,
    string Status,
    string? FeeStatus,
    int Attendance,
    string? Avatar);

public sealed record CreateStudentRequest(
    string FirstName,
    string LastName,
    string Email,
    string? Phone,
    string? DateOfBirth,
    string? Gender,
    string? BloodGroup,
    string? Address,
    string Class,
    string Section,
    string RollNo,
    string AdmissionNo,
    string? ParentName,
    string? ParentPhone,
    string? ParentEmail,
    string Status = "active");

public sealed record UpdateStudentRequest(
    string? FirstName,
    string? LastName,
    string? Email,
    string? Phone,
    string? DateOfBirth,
    string? Gender,
    string? BloodGroup,
    string? Address,
    string? Class,
    string? Section,
    string? RollNo,
    string? AdmissionNo,
    string? ParentName,
    string? ParentPhone,
    string? ParentEmail,
    string? Status);
